const LANE = 'ORDINARY_SINGLE_AGENT_CONTROLLED_IMAGE_ASSIGN_AND_START'
const TRANSPORT = 'PERSONAL_WORKSPACE_CONTROLLED_IMAGE_HTTP_V2'
const OPERATION = 'GENERATE_IMAGE'
const RECOVERY = Object.freeze({ legacyFallbackAllowed: false, unknownOrNotFoundMeans: 'RECOVERY_REQUIRED', replayPolicy: 'EXPLICIT_USER_EXACT_ORIGINAL_KEY_AND_BODY_ONLY' })
const own = (v, k) => Object.prototype.hasOwnProperty.call(v, k)
const object = v => v && typeof v === 'object' && !Array.isArray(v)
const exact = (v, keys) => object(v) && Object.keys(v).length === keys.length && keys.every(k => own(v, k))
const id = v => typeof v === 'string' && v.length > 0 && v.trim() === v && [...v].every(c => { const p = c.codePointAt(0); return p >= 0x20 && p !== 0x7f && !(p >= 0x80 && p <= 0x9f) && !(p >= 0xd800 && p <= 0xdfff) })
const long = v => typeof v === 'string' && /^[1-9][0-9]*$/.test(v) && BigInt(v) <= 9223372036854775807n
const reasons = v => Array.isArray(v) && v.every(id) ? [...v] : null
const ops = (v, allowed = [OPERATION]) => Array.isArray(v) && v.every(x => allowed.includes(x)) && new Set(v).size === v.length ? [...v] : null
const unwrap = result => { const e = result && own(result, 'code') ? result : result?.data ?? result; if (e && own(e, 'code')) { if (![undefined, null, 'E0', '0', 0, '200', 200].includes(e.code)) { const x = new Error(e.msg || e.message || '受控图像办理能力读取被拒绝'); x.code = e.code; x.status = e.status; throw x }; return e.data?.data ?? e.data }; return e?.data ?? e }
export const parseControlledImageBountyCapability = value => {
  const root = ['schemaVersion', 'taskId', 'targetAgentId', 'lane', 'serverLane', 'controlledExecution', 'providerBinding', 'authorization', 'newStart', 'requestedOperations', 'initialOperation', 'inputRefsPolicy', 'maxInputItems', 'originalIntentRecovery']
  if (!exact(value, root) || value.schemaVersion !== 2 || !id(value.taskId) || !id(value.targetAgentId) || value.lane !== LANE || !exact(value.serverLane, ['state', 'blockingReasons']) || !['READY', 'DISABLED', 'NOT_RUNNING', 'UNAVAILABLE'].includes(value.serverLane.state) || !reasons(value.serverLane.blockingReasons) || !exact(value.controlledExecution, ['state', 'transport', 'schemaVersion', 'supportedOperations']) || !exact(value.authorization, ['state', 'paidExecutionAuthorized']) || !exact(value.newStart, ['eligible', 'blockingReasons']) || typeof value.newStart.eligible !== 'boolean' || !reasons(value.newStart.blockingReasons) || value.inputRefsPolicy !== 'TASK_LINKED_REFERENCE' || value.maxInputItems !== 16 || !exact(value.originalIntentRecovery, Object.keys(RECOVERY)) || Object.keys(RECOVERY).some(k => value.originalIntentRecovery[k] !== RECOVERY[k])) return null
  const unavailable = value.authorization.state === 'UNAVAILABLE' && value.authorization.paidExecutionAuthorized === false && value.newStart.eligible === false && value.providerBinding === null && Array.isArray(value.requestedOperations) && value.requestedOperations.length === 0 && value.initialOperation === null && value.controlledExecution.transport === null && value.controlledExecution.schemaVersion === null && Array.isArray(value.controlledExecution.supportedOperations) && value.controlledExecution.supportedOperations.length === 0
  if (unavailable) return Object.freeze({ ...value, controlledObservation: 'UNAVAILABLE' })
  if (!exact(value.providerBinding, ['providerLane', 'bindingId', 'bindingEpoch', 'modelId', 'maxInputItems', 'maxOutboundRequestAttempts', 'precallFenceVersion']) || value.providerBinding.providerLane !== 'CONTROLLED_IMAGE_HTTP_V1' || !id(value.providerBinding.bindingId) || !long(value.providerBinding.bindingEpoch) || !id(value.providerBinding.modelId) || value.providerBinding.maxInputItems !== 16 || value.providerBinding.maxOutboundRequestAttempts !== 1 || value.providerBinding.precallFenceVersion !== 1 || value.controlledExecution.state !== 'READY' || value.controlledExecution.transport !== TRANSPORT || value.controlledExecution.schemaVersion !== 1 || JSON.stringify(ops(value.controlledExecution.supportedOperations)) !== JSON.stringify([OPERATION]) || JSON.stringify(ops(value.requestedOperations)) !== JSON.stringify([OPERATION]) || value.initialOperation !== OPERATION) return null
  const consent = value.authorization.state === 'CONSENT_REQUIRED' && value.authorization.paidExecutionAuthorized === false && value.newStart.eligible === false && value.serverLane.state === 'READY'
  const ready = value.authorization.state === 'READY' && value.authorization.paidExecutionAuthorized === true && value.newStart.eligible === true && value.serverLane.state === 'READY'
  if (!consent && !ready) return null
  return Object.freeze({ ...value, controlledObservation: consent ? 'CONSENT_REQUIRED' : 'READY' })
}
export const capabilityOffersControlledImageConsent = (c, task, agent) => Boolean(c?.controlledObservation === 'CONSENT_REQUIRED' && c.taskId === task?.id && c.targetAgentId === agent?.agentId)
export const loadControlledImageBountyCapability = async ({ agentApi, taskId, targetAgentId, signal }) => {
  if (!id(taskId) || !id(targetAgentId)) return Object.freeze({ controlledObservation: 'MALFORMED' })
  try { const raw = unwrap(await agentApi.get(`/tasks/${encodeURIComponent(taskId)}/point-and-start-controlled-image-capability`, { targetAgentId }, { autoLoading: false, signal })); const parsed = parseControlledImageBountyCapability(raw); return parsed?.taskId === taskId && parsed.targetAgentId === targetAgentId ? parsed : Object.freeze({ controlledObservation: 'MALFORMED' }) } catch (error) { if (error?.status === 404) return Object.freeze({ controlledObservation: 'UNDECLARED' }); return Object.freeze({ controlledObservation: 'UNKNOWN' }) }
}
export const createControlledImageCapabilityObservationFence = ({ getIdentityScope, getAuthorizationGeneration }) => { let epoch = 0; return Object.freeze({ invalidate: () => { epoch++ }, capture: () => { const token = ++epoch; const scope = getIdentityScope(); const generation = getAuthorizationGeneration(); return Object.freeze({ identityScope: scope, authorizationGeneration: generation, isCurrent: () => token === epoch && scope === getIdentityScope() && generation === getAuthorizationGeneration() }) } }) }
